// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdGjIIInBMJ8-zElKuU_nlyvYq0uCqvYY',
    appId: '1:412528871621:web:0d1138a5e42a7ffed9c8ac',
    messagingSenderId: '412528871621',
    projectId: 'mm-flutter-6a9a9',
    authDomain: 'mm-flutter-6a9a9.firebaseapp.com',
    storageBucket: 'mm-flutter-6a9a9.appspot.com',
    measurementId: 'G-L3RB48NPTS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6yk5FjRk_m6SXaIgvJatmKgCYXwyKsuM',
    appId: '1:412528871621:android:670fa76c21551e6dd9c8ac',
    messagingSenderId: '412528871621',
    projectId: 'mm-flutter-6a9a9',
    storageBucket: 'mm-flutter-6a9a9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAodQ8LJHCgN6YgrGDohyPuIMe9Xk-Csto',
    appId: '1:412528871621:ios:8cb22ce959c4a48cd9c8ac',
    messagingSenderId: '412528871621',
    projectId: 'mm-flutter-6a9a9',
    storageBucket: 'mm-flutter-6a9a9.appspot.com',
    iosBundleId: 'com.example.flutterUpgrdeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAodQ8LJHCgN6YgrGDohyPuIMe9Xk-Csto',
    appId: '1:412528871621:ios:8cb22ce959c4a48cd9c8ac',
    messagingSenderId: '412528871621',
    projectId: 'mm-flutter-6a9a9',
    storageBucket: 'mm-flutter-6a9a9.appspot.com',
    iosBundleId: 'com.example.flutterUpgrdeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBdGjIIInBMJ8-zElKuU_nlyvYq0uCqvYY',
    appId: '1:412528871621:web:99299c2335fa969dd9c8ac',
    messagingSenderId: '412528871621',
    projectId: 'mm-flutter-6a9a9',
    authDomain: 'mm-flutter-6a9a9.firebaseapp.com',
    storageBucket: 'mm-flutter-6a9a9.appspot.com',
    measurementId: 'G-Q09BREHQ8C',
  );
}
